import React from 'react';
import Head from 'next/head';
import AppContext from '@context/AppContext';

import useInitialState from '@hooks/useInitialState';
import MainLayout from '@layout/MainLayout';

//CSS
import '@styles/globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';


function MyApp({ Component, pageProps }) {

  const initialState = useInitialState();

  return (
    <>
      <AppContext.Provider value={initialState}>

        <Head>
          <title>Banarica</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <MainLayout>
          <Component {...pageProps} />
        </MainLayout>
      </AppContext.Provider>
    </>
  );
}

export default MyApp;
