import Head from 'next/head'
import { Container } from 'react-bootstrap';

//Components
import Tablero from '../components/Tablero';
import Cards from '../components/Cards';
import SecondLayout from 'layout/SecondLayout';

//CSS


export default function Home() {
  return (
    <div>
      <Head>
        <title>Banarica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <SecondLayout>
          <Container>
            <Tablero />
          </Container>
          <div>
            <Cards></Cards>
          </div>
        </SecondLayout>
      </main>
      <footer >

      </footer>
    </div>
  )
}
