import Head from 'next/head'
import { Container } from 'react-bootstrap';

//Components
import Header from '../containers/Header';
import Tablero from '../components/Tablero';
import Cards from '../components/Cards';

//CSS


export default function Home() {
  return (
    <div>
      <Head>
        <title>Banarica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main >

        <Container>
          <Tablero />
        </Container>

        <Container>
          
            <Cards></Cards>

        </Container>
      </main>

      <footer >

      </footer>
    </div>
  )
}
